#!/usr/bin/env bash
# build_pdfs.sh — render the three solution papers (Markdown -> PDF).
#
# Output:
#   papers_pdf/solution_paper.pdf         (full unified reference, ~17 pp)
#   papers_pdf/solution_paper_task_a.pdf  (User Modeling submission,    ~14 pp)
#   papers_pdf/solution_paper_task_b.pdf  (Recommendation submission,   ~10 pp)
#
# Pipeline:
#   1. Extract title / subtitle / author / date / abstract from each
#      Markdown file's front matter (the H1/H3/Authors/Date/Abstract
#      structure used by the three papers).
#   2. Emit a pandoc-ready Markdown with YAML metadata block + body.
#   3. Run pandoc through a custom NeurIPS / arXiv-style LaTeX template
#      (assets/arxiv_template.tex) with pdflatex.
#
# Dependencies (verified once at startup):
#   - BasicTeX or TeX Live including: mathptmx, helvet, courier, microtype,
#     enumitem, siunitx, titlesec, cleveref, booktabs, caption, hyperref.
#     Install on macOS via: brew install --cask basictex (interactive)
#     followed by: sudo /Library/TeX/texbin/tlmgr install \
#       collection-fontsrecommended collection-latexrecommended enumitem \
#       siunitx titlesec cleveref
#   - pandoc 3.x: brew install pandoc
#   - python3 (for the metadata-extraction helper; uses only stdlib)

set -euo pipefail

# Resolve repo root regardless of where the script is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Make sure BasicTeX's binaries are reachable even when run from contexts
# (e.g. cron, CI) that haven't loaded the macOS path helper.
export PATH="/Library/TeX/texbin:$PATH"

TEMPLATE="$REPO_ROOT/assets/arxiv_template.tex"
OUTDIR="$REPO_ROOT/papers_pdf"
mkdir -p "$OUTDIR"

# --- Step 0: re-render the Mermaid architecture diagram if its source is
# newer than the rendered PNG (or if the PNG is missing). Each paper's §2
# embeds assets/diagrams/architecture.png; the source .mmd is the canonical
# artefact tracked in git, the PNG is regenerated by build.
DIAGRAM_SRC="$REPO_ROOT/assets/diagrams/architecture.mmd"
DIAGRAM_OUT="$REPO_ROOT/assets/diagrams/architecture.png"
if [ -f "$DIAGRAM_SRC" ] && [ ! -f "$DIAGRAM_OUT" -o "$DIAGRAM_SRC" -nt "$DIAGRAM_OUT" ]; then
    echo "  re-rendering Mermaid diagram (source newer than PNG)..."
    npx -y @mermaid-js/mermaid-cli \
        -i "$DIAGRAM_SRC" -o "$DIAGRAM_OUT" \
        -w 1400 --backgroundColor white \
        > /dev/null 2>&1 || {
            echo "  WARN: mermaid render failed — PDFs will use the existing PNG (if any)"
        }
fi

# --- Step 1: extract metadata from each Markdown, emit pandoc-ready version
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

python3 - "$WORKDIR" <<'PY'
import re, sys, pathlib
workdir = sys.argv[1]
for src in ["solution_paper.md", "solution_paper_task_a.md", "solution_paper_task_b.md"]:
    text = pathlib.Path(src).read_text()
    # The flag emoji has no font glyph in our BasicTeX install — substitute.
    text = text.replace("\U0001f1f3\U0001f1ec", "(Nigerian)")
    lines = text.splitlines()
    title = subtitle = author = date = ""
    body_idx = 0
    for i, l in enumerate(lines):
        if l.startswith("# "):
            title = l[2:].strip()
            body_idx = i + 1
            break
    for j in range(body_idx, min(body_idx + 5, len(lines))):
        if lines[j].startswith("### "):
            subtitle = lines[j][4:].strip()
            body_idx = j + 1
            break
    last = body_idx
    for j in range(body_idx, min(body_idx + 12, len(lines))):
        if lines[j].startswith("**Authors**:"):
            author = lines[j].replace("**Authors**:", "").strip()
        elif lines[j].startswith("**Affiliation**:"):
            author += f" — {lines[j].replace('**Affiliation**:', '').strip()}"
        elif lines[j].startswith("**Date**:"):
            date = lines[j].replace("**Date**:", "").strip()
            last = j + 1
    body_idx = max(body_idx, last)
    body = "\n".join(lines[body_idx:])
    m = re.search(r'(?m)^## Abstract\s*\n+(.*?)(?=\n## |\n---\n|\Z)', body, re.DOTALL)
    abstract = m.group(1).strip().replace("\n", " ") if m else ""
    if m:
        body = body[:m.start()] + body[m.end():]
    body = re.sub(r'^(\s*\n|---\n)+', '', body)
    yaml = ["---", f'title: "{title}"']
    if subtitle:  yaml.append(f'subtitle: "{subtitle}"')
    if author:    yaml.append(f'author: "{author}"')
    if date:      yaml.append(f'date: "{date}"')
    if abstract:
        ab = abstract.replace('"', '\\"')
        yaml.append(f'abstract: "{ab}"')
    yaml += ["---", ""]
    pathlib.Path(f"{workdir}/{src}").write_text("\n".join(yaml) + body)
    print(f"  prepared {src} ({len(body)} body chars, abstract={len(abstract)}ch)")
PY

# --- Step 2: pandoc -> .tex, patch longtable for twocolumn, run pdflatex
#
# longtable doesn't work in twocolumn mode, and pandoc 3.x emits it for
# every markdown table. We text-rewrite the .tex output:
#   \begin{longtable}[...]   -> \par\noindent\begin{minipage}{...}\centering\small
#                               \\\begin{tabular}            (colspec follows)
#   \midrule\noalign{}\endhead\bottomrule\noalign{}\endlastfoot
#                            -> \midrule\noalign{}
#                               (strips the longtable structural block; the
#                               misplaced \bottomrule gets re-added below)
#   \end{longtable}         -> \\bottomrule\\end{tabular}\\end{minipage}\par\medskip
#
# pdflatex runs from the repo root with --output-directory=$WORKDIR so the
# image path `assets/diagrams/architecture.png` (relative to repo) resolves.
for tag in solution_paper solution_paper_task_a solution_paper_task_b; do
    out="$OUTDIR/$tag.pdf"
    tex="$WORKDIR/$tag.tex"
    rm -f "$out" "$tex"

    pandoc "$WORKDIR/$tag.md" \
        -o "$tex" \
        --template="$TEMPLATE" \
        --metadata secnumdepth=-1 \
        --standalone

    python3 - "$tex" <<'PY'
import re, sys, pathlib
p = pathlib.Path(sys.argv[1])
src = p.read_text()

# Strategy: rewrite each \begin{longtable}...\end{longtable} block. Wide
# tables (>4 columns OR containing "Goodreads"/multi-domain rows) get
# wrapped in \begin{table*} so they span both columns; narrow tables
# stay inline in a single-column minipage.

def rewrite_longtable(match):
    block = match.group(0)
    # Strip the longtable structural marker block (endhead..endlastfoot)
    # so the inline \bottomrule disappears from between the header and
    # the body rows.
    block = re.sub(
        r'\\midrule\\noalign\{\}\s*\\endhead\s*\\bottomrule\\noalign\{\}\s*\\endlastfoot',
        r'\\midrule\\noalign{}',
        block,
    )
    block = block.replace(r'\endhead', '').replace(r'\endlastfoot', '')

    # Count `\centering` minipage cells in the first row to estimate
    # column width. Pandoc emits one minipage cell per column.
    # Crude but accurate: count `&` separators in the first body line
    # to count columns.
    first_row_match = re.search(r'\\toprule\\noalign\{\}\s*\n(.*?)\\\\\n\\midrule', block, re.DOTALL)
    ncols = 0
    if first_row_match:
        # Number of \begin{minipage}[b] gives column count
        ncols = first_row_match.group(1).count(r'\begin{minipage}[b]')
        if ncols == 0:
            # Simple text-only header — count `&` in first row
            ncols = first_row_match.group(1).count('&') + 1
    wide = ncols >= 5  # 5+ columns → span both columns of the paper

    # Replace \begin{longtable}[<opt>] with appropriate wrapper.
    if wide:
        # Floating wide table spanning both columns.
        open_macro = (
            r'\begin{table*}[!t]\centering\small' '\n'
            r'\begin{tabular}'
        )
        close_macro = r'\bottomrule' + '\n' + r'\end{tabular}' + '\n' + r'\end{table*}'
    else:
        # Inline single-column table.
        open_macro = (
            r'\par\noindent\begin{minipage}{\linewidth}\centering\small' '\n'
            r'\begin{tabular}'
        )
        close_macro = (
            r'\bottomrule' + '\n' + r'\end{tabular}\end{minipage}\par\medskip'
        )
    # Use a lambda for re.sub to avoid backslash-escape interpretation
    # in the replacement string. (re.sub treats `\c`, `\b`, etc. as
    # regex escapes in the replacement, so even raw strings don't help.)
    block = re.sub(r'\\begin\{longtable\}\[[^\]]*\]',
                   lambda _m: open_macro, block)
    block = block.replace(r'\end{longtable}', close_macro)
    return block

src = re.sub(
    r'\\begin\{longtable\}.*?\\end\{longtable\}',
    rewrite_longtable, src, flags=re.DOTALL,
)

# Em-dash removal: pandoc converts markdown em-dash (U+2014) to LaTeX
# `---` (three-hyphen ligature). User wants em-dashes gone, so we
# collapse `---` to a single hyphen. Leaves the en-dash `--` (used for
# numeric ranges like 6.3--13%) untouched.
src = src.replace('---', '-')

p.write_text(src)
PY

    # Run pdflatex from the repo root so image paths (assets/diagrams/...)
    # resolve. --output-directory keeps aux/log/pdf in the workdir.
    if pdflatex -interaction=nonstopmode -output-directory="$WORKDIR" "$tex" > /dev/null 2>&1 \
    && pdflatex -interaction=nonstopmode -output-directory="$WORKDIR" "$tex" > /dev/null 2>&1; then
        mv "${tex%.tex}.pdf" "$out"
        size=$(stat -f%z "$out" 2>/dev/null || stat -c%s "$out")
        pages=$(pdfinfo "$out" 2>/dev/null | awk '/^Pages/ {print $2}')
        echo "  built $tag.pdf — ${size} B, ${pages} pages"
    else
        echo "  FAILED to build $tag.pdf — debug by running:"
        echo "    pdflatex -interaction=nonstopmode -output-directory=$WORKDIR $tex"
        echo "  (preserving WORKDIR for inspection)"
        trap - EXIT
        exit 1
    fi
done
echo "All papers rendered to $OUTDIR/"
